services:
  xray:
    image: ${XRAY_IMAGE:-ghcr.io/xtls/xray-core:latest}
    container_name: xray
    restart: unless-stopped
    ports:
      - "${XRAY_PORT-443}:443/tcp"
    read_only: true
    cap_drop: [ "ALL" ]
    cap_add:  [ "NET_BIND_SERVICE" ]
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    volumes:
      - ./xray/config.json:/usr/local/etc/xray/config.json:ro

  panel:
    image: ${PANEL_IMAGE:-ghcr.io/mhsanaei/3x-ui:latest}
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - "${PANEL_PORT-4242}:2053/tcp"
    depends_on:
      - xray
    # immutable Xray: panel can only read configs
    volumes:
      - ./xray/:/usr/local/etc/xray/:ro
      - ./3xui-data/:/etc/x-ui/