services:
  xray:
    image: ${XRAY_IMAGE:-ghcr.io/xtls/xray-core:latest}
    container_name: xray-cli
    restart: unless-stopped
    ports:
      - "${XRAY_PORT:-443}:443/tcp"
    read_only: true
    cap_drop: [ "ALL" ]
    cap_add:  [ "NET_BIND_SERVICE" ]
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    volumes:
      - ./xray/config.json:/usr/local/etc/xray/config.json:ro
