services:
  panel:
    image: ${PANEL_IMAGE:-ghcr.io/mhsanaei/3x-ui:latest}
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - "${XRAY_PORT:-443}:443/tcp"
      - "127.0.0.1:${PANEL_PORT:-4242}:2053/tcp"
    volumes:
      - ./3xui-data/:/etc/x-ui/
